# This workflow runs ESLint and Prettier when pushing to the main branch to guarantee high code quality.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: frontend CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

defaults:
    run:
        working-directory: labgrid-web-client

jobs:
    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}
        - run: npm run lint
